# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wN0cmr4-w_VOn67LSb-KV4QrlbsWwdtE
"""

# --- Bibliotecas ---
import streamlit as st
import pandas as pd
import joblib
import pickle # Adicionada a importação do pickle
import plotly.express as px

# --- Configuração da Página ---
st.set_page_config(
    page_title="Dashboard de Detecção de Fraudes",
    page_icon="🤖",
    layout="wide"
)

# --- Funções de Cache ---
@st.cache_data
def load_data(filepath):
    """Carrega o dataset inicial."""
    try:
        # Changed delimiter from ';' to ','
        df = pd.read_csv('/content/drive/MyDrive/Projetos/creditcard.csv', delimiter=',', decimal='.')
        return df
    except FileNotFoundError:
        return None

@st.cache_resource
def load_model(model_format):
    """Carrega o modelo treinado no formato escolhido (.joblib ou .pkl)."""
    if model_format == 'Joblib (.joblib)':
        try:
            model = joblib.load('best_fraud_detection_model.joblib')
            return model
        except FileNotFoundError:
            return None
    elif model_format == 'Pickle (.pkl)':
        try:
            with open('best_fraud_detection_model.pkl', 'rb') as file:
                model = pickle.load(file)
            return model
        except FileNotFoundError:
            return None
    return None

@st.cache_resource
def load_scaler(scaler_path):
    """Carrega o scaler salvo."""
    try:
        scaler = joblib.load(scaler_path)
        return scaler
    except FileNotFoundError:
        return None

# --- Barra Lateral (Sidebar) ---
st.sidebar.title("Navegação e Opções")

# Adicionado o seletor para escolher o formato do modelo
model_format_choice = st.sidebar.selectbox(
    "Escolha o formato do modelo para carregar:",
    ('Joblib (.joblib)', 'Pickle (.pkl)')
)

page = st.sidebar.radio("Selecione uma página:", ["Visão Geral", "Análise Exploratória", "Previsão de Fraude"])

# --- Carregamento dos Arquivos com base na seleção ---
df_raw = load_data('creditcard.csv')
model = load_model(model_format_choice)
scaler = load_scaler('scaler.joblib')

# Checagem de erro se algum arquivo não for encontrado
if df_raw is None or model is None or scaler is None:
    st.error("Erro Crítico: Arquivo(s) necessário(s) não encontrado(s).")
    st.info("Por favor, execute o script 'preparar_artefatos.py' e verifique se os arquivos 'creditcard_reduzido.csv', '.joblib' e '.pkl' estão no mesmo diretório.")
    st.stop()

# Mensagem de sucesso na barra lateral
st.sidebar.success(f"Modelo '{model_format_choice}' carregado com sucesso.")

# --- Lógica das Páginas (permanece a mesma) ---

# Página 1: Visão Geral
if page == "Visão Geral":
    st.title("Dashboard Interativo de Detecção de Fraudes")
    st.markdown("""
    Este dashboard utiliza um modelo de Machine Learning para analisar e prever fraudes em transações financeiras.
    - **Dados:** Dataset anonimizado de transações com cartão de crédito.
    - **Modelo:** LightGBM (Gradient Boosting).
    - **Objetivo:** Identificar transações fraudulentas em tempo real e explorar padrões nos dados.
    """)

    st.header("Métricas Gerais do Dataset")
    total_transacoes = df_raw.shape[0]
    fraudes = df_raw['Class'].sum()
    taxa_fraude = (fraudes / total_transacoes) * 100

    col1, col2, col3 = st.columns(3)
    col1.metric("Total de Transações", f"{total_transacoes:,}")
    col2.metric("Total de Fraudes", f"{fraudes}")
    col3.metric("Taxa de Fraude", f"{taxa_fraude:.3f}%")

    st.header("Amostra dos Dados")
    st.dataframe(df_raw.head())

# Página 2: Análise Exploratória
elif page == "Análise Exploratória":
    st.title("Análise Exploratória dos Dados")
    st.markdown("Selecione um gráfico para explorar os padrões das transações.")

    chart_choice = st.selectbox(
        "Escolha o gráfico:",
        ["Distribuição do Valor (Amount) por Classe", "Distribuição do Tempo (Time) por Classe"]
    )

    if chart_choice == "Distribuição do Valor (Amount) por Classe":
        fig = px.histogram(df_raw, x="Amount", color="Class", marginal="box",
                           hover_data=df_raw.columns, log_y=True,
                           title="Distribuição do Valor da Transação por Classe",
                           labels={"Amount": "Valor da Transação", "Class": "Classe (0: Normal, 1: Fraude)"})
        st.plotly_chart(fig, use_container_width=True)

    elif chart_choice == "Distribuição do Tempo (Time) por Classe":
        df_eda = df_raw.copy()
        df_eda['Time_in_Hours'] = df_eda['Time'] / 3600
        fig = px.histogram(df_eda, x="Time_in_Hours", color="Class",
                           title="Distribuição das Transações ao Longo do Tempo (em Horas)",
                           labels={"Time_in_Hours": "Tempo em Horas", "Class": "Classe"})
        st.plotly_chart(fig, use_container_width=True)

# Página 3: Previsão de Fraude
elif page == "Previsão de Fraude":
    st.title("Previsão de Fraude em Tempo Real")
    st.markdown("Insira os dados da transação para obter uma previsão.")

    important_features = ['V14', 'V12', 'V10', 'V17', 'V4', 'V11', 'V3', 'V7', 'V16']

    with st.form("prediction_form"):
        st.header("Insira os valores das features:")

        cols = st.columns(3)
        input_data = {}

        # Obter colunas de features do dataframe (após a limpeza e preparação) para usar como referência
        X_columns = df_raw.drop(['Time', 'Amount', 'Class'], axis=1).columns

        for i, feature in enumerate(important_features):
            with cols[i % 3]:
                min_val = float(df_raw[feature].min())
                max_val = float(df_raw[feature].max())
                median_val = float(df_raw[feature].median())
                input_data[feature] = st.slider(f"Valor de {feature}", min_val, max_val, median_val)

        input_data['Amount'] = st.number_input("Valor da Transação (Amount)", min_value=0.0, value=100.0, step=10.0)

        submitted = st.form_submit_button("Realizar Previsão")

    if submitted:
        new_transaction = pd.DataFrame([input_data])

        for col in X_columns:
            if col not in new_transaction.columns:
                new_transaction[col] = df_raw[col].median()

        new_transaction['scaled_Amount'] = scaler.transform(new_transaction[['Amount']])
        new_transaction_processed = new_transaction.drop('Amount', axis=1)
        # Garantir a ordem correta das colunas
        new_transaction_processed = new_transaction_processed[X_columns]

        prediction = model.predict(new_transaction_processed)[0]
        probability = model.predict_proba(new_transaction_processed)[0][1]

        st.header("Resultado da Previsão")
        if prediction == 1:
            st.error("Previsão: TRANSAÇÃO FRAUDULENTA", icon="🚨")
        else:
            st.success("Previsão: Transação Normal", icon="✅")

        st.metric("Probabilidade de ser Fraude:", f"{probability:.2%}")

        with st.expander("Ver dados de entrada da previsão"):
            st.write(new_transaction_processed)